version: 2

models:
  - name: fct_transactions
    description: "Fato de transações consolidado com granularidade por transação"

    columns:
      - name: transaction_id
        description: "Identificador único da transação"
        tests:
          - not_null
          - unique

      - name: user_id
        description: "Identificador do usuário associado à transação"
        tests:
          - not_null

      - name: amount
        description: "Valor da transação"
        tests:
          - not_null

      - name: transaction_type
        description: "Tipo da transação (income ou expense)"
        tests:
          - accepted_values:
              arguments:
                values: ["income", "expense"]
